// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-trips.ts
import { createClient } from "npm:@supabase/supabase-js@2.110.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_trips_default = defineTool({
  name: "list_trips",
  title: "List trips",
  description: "List trip records for BSH Taxi Service, optionally filtered by date range, payment status, or driver name. Returns up to `limit` most recent trips.",
  inputSchema: {
    from_date: z.string().describe("Optional inclusive start date in YYYY-MM-DD format.").optional(),
    to_date: z.string().describe("Optional inclusive end date in YYYY-MM-DD format.").optional(),
    payment_status: z.enum(["Paid", "Pending"]).describe("Optional filter for payment status.").optional(),
    driver_name: z.string().describe("Optional case-insensitive driver name substring filter.").optional(),
    limit: z.number().int().describe("Maximum rows to return. Defaults to 50, max 500.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const limit = Math.min(Math.max(input.limit ?? 50, 1), 500);
    let q = supabaseForUser(ctx).from("trips").select("*").order("date", { ascending: false }).limit(limit);
    if (input.from_date) q = q.gte("date", input.from_date);
    if (input.to_date) q = q.lte("date", input.to_date);
    if (input.payment_status) q = q.eq("payment_status", input.payment_status);
    if (input.driver_name) q = q.ilike("driver_name", `%${input.driver_name}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { trips: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/create-trip.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.110.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_trip_default = defineTool2({
  name: "create_trip",
  title: "Create trip",
  description: "Insert a new trip record for BSH Taxi Service. Amounts default to 0. Payment status must be 'Paid' or 'Pending'.",
  inputSchema: {
    date: z2.string().describe("Trip date in YYYY-MM-DD format."),
    customer_name: z2.string().describe("Customer full name."),
    customer_number: z2.string().describe("Customer phone number."),
    driver_name: z2.string().describe("Assigned driver name."),
    driver_number: z2.string().describe("Assigned driver phone number."),
    from_location: z2.string(),
    to_location: z2.string(),
    fuel_type: z2.string().describe("Fuel type, e.g. Petrol, Diesel, CNG."),
    payment_mode: z2.string().describe("Payment mode, e.g. Cash, UPI, Bank."),
    payment_status: z2.enum(["Paid", "Pending"]).optional(),
    trip_amount: z2.number().optional(),
    driver_amount: z2.number().optional(),
    commission: z2.number().optional(),
    fuel_amount: z2.number().optional(),
    tolls: z2.number().optional(),
    car_number: z2.string().optional(),
    company: z2.string().optional(),
    starting_km: z2.number().optional(),
    ending_km: z2.number().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("trips").insert({ ...input, created_by: ctx.getUserId() }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Trip created: ${data.id}` }],
      structuredContent: { trip: data }
    };
  }
});

// src/lib/mcp/tools/list-drivers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@2.110.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_drivers_default = defineTool3({
  name: "list_drivers",
  title: "List drivers",
  description: "List drivers in the Driver Management module, optionally filtered by status or name.",
  inputSchema: {
    status: z3.enum(["active", "inactive"]).optional(),
    name: z3.string().describe("Case-insensitive substring on driver name.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("drivers").select("*").order("name");
    if (input.status) q = q.eq("status", input.status);
    if (input.name) q = q.ilike("name", `%${input.name}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { drivers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-maintenance.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@2.110.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_maintenance_default = defineTool4({
  name: "list_maintenance",
  title: "List maintenance records",
  description: "List vehicle maintenance/service records, optionally filtered by date range or car number.",
  inputSchema: {
    from_date: z4.string().describe("YYYY-MM-DD").optional(),
    to_date: z4.string().describe("YYYY-MM-DD").optional(),
    car_number: z4.string().optional(),
    limit: z4.number().int().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const limit = Math.min(Math.max(input.limit ?? 50, 1), 500);
    let q = supabaseForUser4(ctx).from("maintenance").select("*").order("date", { ascending: false }).limit(limit);
    if (input.from_date) q = q.gte("date", input.from_date);
    if (input.to_date) q = q.lte("date", input.to_date);
    if (input.car_number) q = q.eq("car_number", input.car_number);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { maintenance: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@2.110.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var financial_summary_default = defineTool5({
  name: "financial_summary",
  title: "Financial summary",
  description: "Compute a financial summary for BSH Taxi Service in the given date range: totals for revenue, driver amounts, commission, fuel, tolls, profit, plus pending payments and trip count. Profit = Trip - Driver - Commission - Fuel - Tolls.",
  inputSchema: {
    from_date: z5.string().describe("Inclusive start date YYYY-MM-DD."),
    to_date: z5.string().describe("Inclusive end date YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    const { data: trips, error } = await sb.from("trips").select("trip_amount,driver_amount,commission,fuel_amount,tolls,payment_status").gte("date", from_date).lte("date", to_date);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const s = {
      trip_count: trips?.length ?? 0,
      total_revenue: 0,
      total_driver_amount: 0,
      total_commission: 0,
      total_fuel: 0,
      total_tolls: 0,
      total_profit: 0,
      pending_amount: 0
    };
    for (const t of trips ?? []) {
      s.total_revenue += Number(t.trip_amount || 0);
      s.total_driver_amount += Number(t.driver_amount || 0);
      s.total_commission += Number(t.commission || 0);
      s.total_fuel += Number(t.fuel_amount || 0);
      s.total_tolls += Number(t.tolls || 0);
      if (t.payment_status === "Pending") s.pending_amount += Number(t.trip_amount || 0);
    }
    s.total_profit = s.total_revenue - s.total_driver_amount - s.total_commission - s.total_fuel - s.total_tolls;
    return {
      content: [{ type: "text", text: JSON.stringify(s, null, 2) }],
      structuredContent: s
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hecnhsynlpachotmpmjg";
var mcp_default = defineMcp({
  name: "bsh-taxi-mcp",
  title: "BSH Taxi Service MCP",
  version: "0.1.0",
  instructions: "Tools for BSH Taxi Service management. Use these to list trips, drivers, and maintenance records, create new trip entries, and compute financial summaries (profit = trip - driver - commission - fuel - tolls). All calls act as the signed-in app user and respect the app's row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_trips_default,
    create_trip_default,
    list_drivers_default,
    list_maintenance_default,
    financial_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
