// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hecnhsynlpachotmpmjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlY25oc3lubHBhY2hvdG1wbWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODk3MzAsImV4cCI6MjA3MDA2NTczMH0.TDFXEUsMFXXa_pO2jtXeid701V1Wib-x9lQ3keakmOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});